---
- name: Install Nerd Font for Debian/Ubuntu
  when: ansible_os_family == "Debian"
  block:
    - name: Ensure font directory exists
      file:
        path: '{{ ansible_env.HOME }}/.local/share/fonts'
        state: directory
        mode: "0755"
    - name: Download Nerd Font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf
        dest: '{{ ansible_env.HOME }}/.local/share/fonts/DroidSansMNerdFont-Regular.otf'
- name: Install Nerd Font (macOS)
  community.general.homebrew_cask:
    name: font-droid-sans-mono-nerd-font
    state: present
  when: ansible_system == "Darwin"
